import '../styles/globals.css'
import type { AppProps } from 'next/app'
import React from 'react'
import Navbar from '../components/navbar'
import Head from 'next/head'

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <React.Fragment>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <Navbar></Navbar>
      </header>
      <Component {...pageProps} />
    </React.Fragment>
  )
}

export default MyApp
