import '../styles/globals.css'
import type { AppProps } from 'next/app'
import React from 'react'
import Navbar from '../components/navbar'
import Head from 'next/head'
import { Provider } from "react-redux";
import store from "../store/store";
import "../styles/globals.css";

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <React.Fragment>
      <Provider store={store}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className=''>
          <header className='backdrop-blur z-40 fixed top-0 right-0 left-0 border-b-2 border-solid border-slate-500/10 h-16'>
            <Navbar></Navbar>
          </header>
          <Component {...pageProps} />
        </div>
      </Provider>
    </React.Fragment >
  )
}

export default MyApp
